In [2]:
import numpy as np
z = np.zeros(4,)
z

array([0., 0., 0., 0.])

In [3]:
X = np.random.random((10, 3))
C = np.random.random((3, 3))


In [4]:
z = np.zeros(10,)
z[0] = 1
z

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
for x_idx in range(len(X)):
    dist_ls = []
    for c in C:
        dist = np.sqrt(np.sum((X[x_idx] - c) ** 2))
        dist_ls.append(dist)
    k = dist_ls.index(min(dist_ls))
    z[x_idx] = k

print(z)

[2. 0. 0. 1. 1. 1. 0. 0. 0. 0.]


In [6]:
K = 3
for k in range(K):
    print(k)

0
1
2


In [7]:
for k in range(K):
    x_ls = []
    for x_idx in range(len(z)):
        if z[x_idx] == k:
            x_ls.append(X[x_idx])
    centre = np.array(x_ls).mean(axis=0)
    C[k] = centre

C

array([[0.53810309, 0.84372326, 0.45912406],
       [0.77833423, 0.16927708, 0.70668522],
       [0.14358935, 0.57081819, 0.03632692]])

In [8]:
from kmeans import kmeans_loss
msd = kmeans_loss(X, C, z)
print(msd)

0.11325298696404493


In [9]:
total_sd = 0
for x_idx in range(len(X)):
    k = z[x_idx]
    c = C[int(k)]
    sd = np.sum((X[x_idx] - c) ** 2)
    total_sd += sd

msd = total_sd / X.shape[0]
msd

0.11325298696404493

In [10]:
ls = [1, 2, 3, 4]
ls2 = [i / 2 for i in ls]
max(ls2)

2.0

In [11]:
if 2 in ls:
    print("yes")

yes
