In [2]:
import numpy as np
z = np.zeros(4,)
z

array([0., 0., 0., 0.])

In [14]:
X = np.random.random((10, 3))
C = np.random.random((3, 3))


[1, 1, 2, 2, 2, 0, 2, 1, 2, 2]

In [34]:
z = np.zeros(10,)
z[0] = 1
z

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
for x_idx in range(len(X)):
    dist_ls = []
    for c in C:
        dist = np.sqrt(np.sum((X[x_idx] - c) ** 2))
        dist_ls.append(dist)
    k = dist_ls.index(min(dist_ls))
    z[x_idx] = k

print(z)

[1. 2. 2. 2. 1. 0. 2. 1. 2. 2.]


In [24]:
K = 3
for k in range(K):
    print(k)

0
1
2


In [39]:
for k in range(K):
    x_ls = []
    for x_idx in range(len(z)):
        if z[x_idx] == k:
            x_ls.append(X[x_idx])
    centre = np.array(x_ls).mean(axis=0)
    C[k] = centre

C

array([[0.95605813, 0.51851339, 0.44919246],
       [0.51678934, 0.18196144, 0.90007416],
       [0.22151369, 0.65283059, 0.24623325]])

In [40]:
from kmeans import kmeans_loss
msd = kmeans_loss(X, C, z)
print(msd)

None


In [50]:
total_sd = 0
for x_idx in range(len(X)):
    k = z[x_idx]
    c = C[int(k)]
    sd = np.sum((X[x_idx] - c) ** 2)
    total_sd += sd

msd = total_sd / X.shape[0]
msd

0.1320602263372009

In [54]:
ls = [1, 2, 3, 4]
ls2 = [i / 2 for i in ls]
max(ls2)

2.0