In [1]:
import numpy as np

np.random.seed(42)
print(np.random.rand())

0.3745401188473625


In [2]:
from neuralnet import random_init

w = random_init([6, 4])
print(w)

ImportError: cannot import name 'random_init' from 'neuralnet' (/Users/anyxling/Downloads/cmu_10601_hws/hw5/handout/neuralnet.py)

In [6]:
from neuralnet import SoftMaxCrossEntropy
sc = SoftMaxCrossEntropy
z = np.array([2.0, 1.0, 0.1])
softmax = sc._softmax(sc, z)
# max = np.argmax(softmax)
softmax

array([0.65900114, 0.24243297, 0.09856589])

In [4]:
y_arr = np.zeros(3)
y_arr[0] = 1
y_arr

array([1., 0., 0.])

In [7]:
# y_hat_arr = np.array([0, 1, 0])
loss = sc._cross_entropy(sc, 1, softmax)
loss

1.4170300162778335

In [8]:
x = np.array([2, 3, 4])
x_b = np.insert(x, 0, 1.0)
x_b

array([1, 2, 3, 4])

In [10]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  
y = np.array([1, 0, 1]) 
for tuple in zip(X, y):
    print(tuple)

(array([1, 2, 3]), 1)
(array([4, 5, 6]), 0)
(array([7, 8, 9]), 1)
