In [1]:
import numpy as np

np.random.seed(42)
print(np.random.rand())

0.3745401188473625


In [2]:
from neuralnet import random_init

w = random_init([6, 4])
print(w)

[[ 0.09200346  0.03990241  0.09997346 -0.05598654]
 [-0.02778873  0.0479682   0.09929115 -0.0367306 ]
 [-0.07269108 -0.023204   -0.03589614 -0.02671705]
 [ 0.04193031  0.08002849  0.00682309 -0.05054125]
 [ 0.03436131  0.01234582  0.00851198  0.07868952]
 [ 0.06855591 -0.03879748  0.02623396  0.03604777]]


In [5]:
from neuralnet import SoftMaxCrossEntropy
sc = SoftMaxCrossEntropy
z = np.array([2.0, 1.0, 0.1])
sc._softmax(sc, z)

array([0.65900114, 0.24243297, 0.09856589])